package com.driverinfo.hibernateEntity;
// Generated 2016-10-26 10:27:41 by Hibernate Tools 4.3.1.Final


/**
 * Area generated by hbm2java
 */

public class Area implements java.io.Serializable {

	private Integer id;
	private int code;
	private String name;
	private String fathercode;

	public Area() {
	}

	public Area(int code) {
		this.code = code;
	}

	public Area(int code, String name, String fathercode) {
		this.code = code;
		this.name = name;
		this.fathercode = fathercode;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public String getFathercode() {
		return this.fathercode;
	}

	public void setFathercode(String fathercode) {
		this.fathercode = fathercode;
	}

}
