package com.driverinfo.hibernateEntity;
// Generated 2016-10-26 10:27:41 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Driver generated by hbm2java
 */

public class Driver implements java.io.Serializable {

	private Integer id;
	private Car car;
	private Company company;
	private String name;
	private Integer sex;
	private String sfzh;
	private String zgzh;
	private String address;
	private String lxdh;
	private String driverNo;
	private Integer status;
	private String driverLevel;
	private Date createtime;
	private Date updatetime;
	private Integer code;

	public Driver() {
	}

	public Driver(String name) {
		this.name = name;
	}

	public Driver(Car car, Company company, String name, Integer sex, String sfzh, String zgzh, String address,
			String lxdh, String driverNo, Integer status, String driverLevel, Date createtime, Date updatetime,
			Integer code) {
		this.car = car;
		this.company = company;
		this.name = name;
		this.sex = sex;
		this.sfzh = sfzh;
		this.zgzh = zgzh;
		this.address = address;
		this.lxdh = lxdh;
		this.driverNo = driverNo;
		this.status = status;
		this.driverLevel = driverLevel;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.code = code;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	
	public String getSfzh() {
		return this.sfzh;
	}

	public void setSfzh(String sfzh) {
		this.sfzh = sfzh;
	}

	
	public String getZgzh() {
		return this.zgzh;
	}

	public void setZgzh(String zgzh) {
		this.zgzh = zgzh;
	}

	
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	
	public String getLxdh() {
		return this.lxdh;
	}

	public void setLxdh(String lxdh) {
		this.lxdh = lxdh;
	}

	
	public String getDriverNo() {
		return this.driverNo;
	}

	public void setDriverNo(String driverNo) {
		this.driverNo = driverNo;
	}


	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	
	public String getDriverLevel() {
		return this.driverLevel;
	}

	public void setDriverLevel(String driverLevel) {
		this.driverLevel = driverLevel;
	}


	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

}
