package com.driverinfo.hibernateEntity;
// Generated 2016-10-26 10:27:41 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer id;
	private String name;
	private String title;
	private Integer enable;
	private int level;
	private String desciption;
	private Integer creator;
	private Date createtime;
	private Date updatetime;
	private Integer areaid;
	private Set roleAuths = new HashSet(0);
	private Set userRoles = new HashSet(0);

	public Role() {
	}

	public Role(String name, String title, int level, String desciption) {
		this.name = name;
		this.title = title;
		this.level = level;
		this.desciption = desciption;
	}

	public Role(String name, String title, Integer enable, int level, String desciption, Integer creator,
			Date createtime, Date updatetime, Integer areaid, Set roleAuths, Set userRoles) {
		this.name = name;
		this.title = title;
		this.enable = enable;
		this.level = level;
		this.desciption = desciption;
		this.creator = creator;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.areaid = areaid;
		this.roleAuths = roleAuths;
		this.userRoles = userRoles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getEnable() {
		return this.enable;
	}

	public void setEnable(Integer enable) {
		this.enable = enable;
	}

	
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	
	public String getDesciption() {
		return this.desciption;
	}

	public void setDesciption(String desciption) {
		this.desciption = desciption;
	}

	
	public Integer getCreator() {
		return this.creator;
	}

	public void setCreator(Integer creator) {
		this.creator = creator;
	}

	
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	
	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	
	public Integer getAreaid() {
		return this.areaid;
	}

	public void setAreaid(Integer areaid) {
		this.areaid = areaid;
	}

	
	public Set getRoleAuths() {
		return this.roleAuths;
	}

	public void setRoleAuths(Set roleAuths) {
		this.roleAuths = roleAuths;
	}

	
	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

}
